In [2]:
import pandas as pd

earnings = pd.read_csv(
    "../02_Cleaned_Data/bank_earnings.csv"
)

earnings.head()

,financial_year,year,bank_name,interest_earned,other_income,total_income,interest_expended,operating_expenses,net_interest_income,provisions_contingencies,operating_profit,net_profit
0,FY2024-25,2025,BANK OF BARODA,121441.6394,16647.3330,138088.9724,75782.9638,29871.3807,45658.6756,12853.4758,32434.6279,19581.1521
1,FY2024-25,2025,BANK OF INDIA,70826.2982,8993.6226,79819.9208,46432.3503,16975.4609,24393.9479,7193.0897,16412.1096,9219.0199
2,FY2024-25,2025,BANK OF MAHARASHTRA,24947.4517,3454.1731,28401.6248,13281.8809,5800.7149,11665.5708,3799.2431,9319.0290,5519.7859
3,FY2024-25,2025,CANARA BANK,119755.0692,22452.8027,142207.8719,82683.1127,28134.4954,37071.9565,14363.5923,31390.2638,17026.6715
4,FY2024-25,2025,CENTRAL BANK OF INDIA,33665.8529,5854.5882,39520.4411,19768.9629,11627.1658,13896.8900,4339.0546,8124.3124,3785.2578

In [9]:
bob = earnings[
    (earnings["bank_name"] == "BANK OF BARODA")
]

bob

,financial_year,year,bank_name,interest_earned,other_income,total_income,interest_expended,operating_expenses,net_interest_income,provisions_contingencies,operating_profit,net_profit
0,FY2024-25,2025,BANK OF BARODA,121441.6394,16647.3330,138088.9724,75782.9638,29871.3807,45658.6756,12853.4758,32434.6279,19581.1521
93,FY2023-24,2024,BANK OF BARODA,112605.9462,14495.3661,127101.3123,67884.4113,28251.6756,44721.5349,13176.4408,30965.2254,17788.7846
188,FY2022-23,2023,BANK OF BARODA,89588.5407,10025.8359,99614.3766,48232.5323,24518.3124,41356.0084,12753.9152,26863.5319,14109.6167
282,FY2021-22,2022,BANK OF BARODA,69880.7803,11483.9503,81364.7306,37259.4421,21716.4388,32621.3382,15116.5681,22388.8497,7272.2816
376,FY2020-21,2021,BANK OF BARODA,70495.0621,12933.9681,83429.0302,41686.0359,20543.6560,28809.0262,20370.3801,21199.3383,828.9582
469,FY2019-20,2020,BANK OF BARODA,75983.6550,10317.3238,86300.9788,48532.3695,18872.3909,27451.2855,18350.0309,18896.2184,546.1875
567,FY2018-19,2019,BANK OF BARODA,49770.6060,6294.4948,56065.1008,31290.3004,11287.9781,18480.3056,13053.2998,13486.8223,433.5225
661,FY2017-18,2018,BANK OF BARODA,43648.5418,6657.1527,50305.6945,28126.7669,10173.3696,15521.7749,14437.3702,12005.5580,-2431.8122
761,FY2016-17,2017,BANK OF BARODA,42199.9298,6758.0609,48957.9907,28686.5191,9296.4023,13513.4107,9591.9333,10975.0693,1383.1360
857,FY2015-16,2016,BANK OF BARODA,44061.2774,4998.8616,49060.1390,31321.4257,8923.1371,12739.8517,14211.1135,8815.5762,-5395.5373

In [4]:
financials=pd.read_csv(
    "../02_Cleaned_Data/bank_financials.csv")

financials.head()

,financial_year,year,bank_name,total_assets,investments,advances,fixed_assets,other_assets,capital,reserves_surplus,deposits,borrowings,other_liabilities_provisions,total_liabilities
0,FY2024-25,2025,BANK OF BARODA,1.781247e+06,385398.4460,1.209558e+06,12376.2569,48065.5179,1035.5336,135890.1506,1.472035e+06,123716.1790,NaN,1.781247e+06
1,FY2024-25,2025,BANK OF INDIA,1.042582e+06,259111.8048,6.496570e+05,11938.7144,21593.4781,4553.4070,74048.0346,8.165415e+05,123856.4269,NaN,1.042582e+06
2,FY2024-25,2025,BANK OF MAHARASHTRA,3.691422e+05,82004.7908,2.360838e+05,2915.5869,5943.1137,7691.5550,20797.7081,3.071426e+05,23852.5150,NaN,3.691422e+05
3,FY2024-25,2025,CANARA BANK,1.682850e+06,380343.3966,1.049155e+06,10215.1494,37795.8566,1814.1303,98085.9766,1.456883e+06,89665.1181,NaN,1.682850e+06
4,FY2024-25,2025,CENTRAL BANK OF INDIA,4.791281e+05,141435.2480,2.824199e+05,5204.2772,13871.8807,9051.4012,27454.6828,4.126971e+05,21591.9465,NaN,4.791281e+05

In [7]:
ratios=pd.read_csv("../02_Cleaned_Data/bank_ratios.csv")
ratios.head()

,financial_year,year,bank_name,cash_deposit_ratio,credit_deposit_ratio,investment_deposit_ratio,credit_plus_investment_deposit_ratio,deposits_to_total_liabilities,demand_savings_to_total_deposits,priority_sector_advances_to_total_advances,...,return_on_advances,return_on_investments,return_on_advances_adjusted_cost_of_funds,return_on_investments_adjusted_cost_of_funds,business_per_employee_lakh,profit_per_employee_lakh,capital_adequacy_ratio,capital_adequacy_tier1,capital_adequacy_tier2,net_npa_to_net_advances
0,FY2024-25,2025,BANK OF BARODA,3.808911,82.169108,26.181340,108.350447,82.640677,37.816087,26.668555,...,8.179076,6.871883,3.169112,1.861919,3433.0,26.00,17.19,14.79,2.40,0.58
1,FY2024-25,2025,BANK OF INDIA,6.335309,79.562037,31.732840,111.294877,78.319166,34.837855,30.719409,...,8.252782,7.076530,2.974105,1.797853,2821.0,18.15,17.77,15.47,2.30,0.82
2,FY2024-25,2025,BANK OF MAHARASHTRA,12.369822,76.864555,26.699256,103.563811,83.204424,53.283738,38.330711,...,8.842750,7.133973,4.484185,2.775408,3744.0,37.83,20.53,16.86,3.67,0.18
3,FY2024-25,2025,CANARA BANK,6.177473,72.013668,26.106650,98.120319,86.572393,28.488927,41.133395,...,8.864168,6.667294,3.194159,0.997285,2930.0,21.00,16.33,14.37,1.96,0.70
4,FY2024-25,2025,CENTRAL BANK OF INDIA,5.556399,68.432718,34.270954,102.703673,86.135027,48.971073,45.608611,...,8.496754,7.073480,3.784843,2.361569,2131.0,12.00,17.02,14.73,2.29,0.55