In [1]:
import pandas as pd

financials = pd.read_csv("../02_Cleaned_Data/bank_financials.csv")
earnings = pd.read_csv("../02_Cleaned_Data/bank_earnings.csv")
crar = pd.read_csv("../02_Cleaned_Data/bank_crar.csv")
npa = pd.read_csv("../02_Cleaned_Data/bank_npa.csv")
ratios = pd.read_csv("../02_Cleaned_Data/bank_ratios.csv")

In [2]:
master=financials.copy()

In [4]:
master = master.merge(
    earnings,
    on=["financial_year", "year", "bank_name"],
    how="left"
)

In [5]:
master=master.merge(crar,on=["financial_year", "year", "bank_name"],how="left")

In [6]:
master=master.merge(npa,on=["financial_year", "year", "bank_name"],how="left")

In [7]:
master = master.merge(
    ratios[
        [
            "financial_year",
            "year",
            "bank_name",
            "return_on_assets",
            "return_on_equity",
            "net_npa_to_net_advances"
        ]
    ],
    on=["financial_year", "year", "bank_name"],
    how="left"
)

In [8]:
master.head()

,financial_year,year,bank_name,total_assets,investments,advances,fixed_assets,other_assets,capital,reserves_surplus,...,gross_npa_opening,gross_npa_additions,gross_npa_reduction,gross_npa_writeoff,gross_npa_closing,net_npa_opening,net_npa_closing,return_on_assets,return_on_equity,net_npa_to_net_advances
0,FY2024-25,2025,BANK OF BARODA,1.781247e+06,385398.4460,1.209558e+06,12376.2569,48065.5179,1035.5336,135890.1506,...,31833.63,9310.13,4320.06,8988.82,27834.88,7213.340000,6994.220000,1.16,15.718410,0.58
1,FY2024-25,2025,BANK OF INDIA,1.042582e+06,259111.8048,6.496570e+05,11938.7144,21593.4781,4553.4070,74048.0346,...,29182.77,7588.56,7265.87,7756.57,21748.89,6845.260000,5358.490000,0.90,12.501882,0.82
2,FY2024-25,2025,BANK OF MAHARASHTRA,3.691422e+05,82004.7908,2.360838e+05,2915.5869,5943.1137,7691.5550,20797.7081,...,3833.05,1687.86,540.80,795.59,4184.52,408.990151,431.780151,1.75,22.921194,0.18
3,FY2024-25,2025,CANARA BANK,1.682850e+06,380343.3966,1.049155e+06,10215.1494,37795.8566,1814.1303,98085.9766,...,40605.00,8544.00,3269.00,14350.00,31530.00,11823.000000,7353.000000,1.09,18.224505,0.70
4,FY2024-25,2025,CENTRAL BANK OF INDIA,4.791281e+05,141435.2480,2.824199e+05,5204.2772,13871.8807,9051.4012,27454.6828,...,11340.34,3494.58,2270.78,3339.36,9224.78,3001.950000,1543.250000,0.86,11.027049,0.55

In [9]:
print(master.shape)
print(master.columns.tolist())

(943, 36)
['financial_year', 'year', 'bank_name', 'total_assets', 'investments', 'advances', 'fixed_assets', 'other_assets', 'capital', 'reserves_surplus', 'deposits', 'borrowings', 'other_liabilities_provisions', 'total_liabilities', 'interest_earned', 'other_income', 'total_income', 'interest_expended', 'operating_expenses', 'net_interest_income', 'provisions_contingencies', 'operating_profit', 'net_profit', 'crar', 'tier1_crar', 'tier2_crar', 'gross_npa_opening', 'gross_npa_additions', 'gross_npa_reduction', 'gross_npa_writeoff', 'gross_npa_closing', 'net_npa_opening', 'net_npa_closing', 'return_on_assets', 'return_on_equity', 'net_npa_to_net_advances']

In [11]:
master.duplicated(
    subset=["bank_name", "year"]
).sum()

np.int64(0)

In [12]:
master.isna().sum().sort_values(ascending=False)

other_liabilities_provisions    565
gross_npa_writeoff              342
net_npa_to_net_advances         333
net_npa_closing                 329
net_npa_opening                 328
gross_npa_additions             318
gross_npa_reduction             315
gross_npa_closing               229
gross_npa_opening               227
borrowings                      143
advances                         48
tier2_crar                       35
investments                      25
deposits                         22
interest_expended                18
return_on_equity                 13
return_on_assets                 12
tier1_crar                       11
crar                             10
fixed_assets                      8
reserves_surplus                  3
provisions_contingencies          3
year                              0
financial_year                    0
total_assets                      0
bank_name                         0
other_assets                      0
capital                           0
net_interest_income               0
operating_expenses                0
total_income                      0
other_income                      0
total_liabilities                 0
interest_earned                   0
operating_profit                  0
net_profit                        0
dtype: int64

In [14]:
master[
    ["bank_name", "year", "gross_npa_closing", "net_npa_closing"]
].isna().groupby(master["year"]).sum()

      bank_name  year  gross_npa_closing  net_npa_closing
year
2016          0     0                 20               24
2017          0     0                 15               23
2018          0     0                 18               33
2019          0     0                 15               28
2020          0     0                 22               36
2021          0     0                 25               36
2022          0     0                 25               37
2023          0     0                 25               36
2024          0     0                 30               38
2025          0     0                 34               38

In [16]:
master.to_csv("../02_Cleaned_Data/bank_master.csv", index=False)