In [2]:
import pandas as pd

master=pd.read_csv("../02_Cleaned_Data/bank_master.csv")

In [3]:
master.head()

,financial_year,year,bank_name,total_assets,investments,advances,fixed_assets,other_assets,capital,reserves_surplus,...,gross_npa_opening,gross_npa_additions,gross_npa_reduction,gross_npa_writeoff,gross_npa_closing,net_npa_opening,net_npa_closing,return_on_assets,return_on_equity,net_npa_to_net_advances
0,FY2024-25,2025,BANK OF BARODA,1.781247e+06,385398.4460,1.209558e+06,12376.2569,48065.5179,1035.5336,135890.1506,...,31833.63,9310.13,4320.06,8988.82,27834.88,7213.340000,6994.220000,1.16,15.718410,0.58
1,FY2024-25,2025,BANK OF INDIA,1.042582e+06,259111.8048,6.496570e+05,11938.7144,21593.4781,4553.4070,74048.0346,...,29182.77,7588.56,7265.87,7756.57,21748.89,6845.260000,5358.490000,0.90,12.501882,0.82
2,FY2024-25,2025,BANK OF MAHARASHTRA,3.691422e+05,82004.7908,2.360838e+05,2915.5869,5943.1137,7691.5550,20797.7081,...,3833.05,1687.86,540.80,795.59,4184.52,408.990151,431.780151,1.75,22.921194,0.18
3,FY2024-25,2025,CANARA BANK,1.682850e+06,380343.3966,1.049155e+06,10215.1494,37795.8566,1814.1303,98085.9766,...,40605.00,8544.00,3269.00,14350.00,31530.00,11823.000000,7353.000000,1.09,18.224505,0.70
4,FY2024-25,2025,CENTRAL BANK OF INDIA,4.791281e+05,141435.2480,2.824199e+05,5204.2772,13871.8807,9051.4012,27454.6828,...,11340.34,3494.58,2270.78,3339.36,9224.78,3001.950000,1543.250000,0.86,11.027049,0.55

In [5]:
master.columns.to_list

<bound method IndexOpsMixin.tolist of Index(['financial_year', 'year', 'bank_name', 'total_assets', 'investments',
       'advances', 'fixed_assets', 'other_assets', 'capital',
       'reserves_surplus', 'deposits', 'borrowings',
       'other_liabilities_provisions', 'total_liabilities', 'interest_earned',
       'other_income', 'total_income', 'interest_expended',
       'operating_expenses', 'net_interest_income', 'provisions_contingencies',
       'operating_profit', 'net_profit', 'crar', 'tier1_crar', 'tier2_crar',
       'gross_npa_opening', 'gross_npa_additions', 'gross_npa_reduction',
       'gross_npa_writeoff', 'gross_npa_closing', 'net_npa_opening',
       'net_npa_closing', 'return_on_assets', 'return_on_equity',
       'net_npa_to_net_advances'],
      dtype='str')>

In [8]:
#Finding the total unique banks in the dataset

master['bank_name'].unique().tolist()

['BANK OF BARODA',
 'BANK OF INDIA',
 'BANK OF MAHARASHTRA',
 'CANARA BANK',
 'CENTRAL BANK OF INDIA',
 'INDIAN BANK',
 'INDIAN OVERSEAS BANK',
 'PUNJAB AND SIND BANK',
 'PUNJAB NATIONAL BANK',
 'STATE BANK OF INDIA',
 'UCO BANK',
 'UNION BANK OF INDIA',
 'AXIS BANK LIMITED',
 'BANDHAN BANK LIMITED',
 'CITY UNION BANK LIMITED',
 'CSB BANK LIMITED',
 'DCB BANK LIMITED',
 'DHANLAXMI BANK LIMITED',
 'FEDERAL BANK LTD',
 'HDFC BANK LTD.',
 'ICICI BANK LIMITED',
 'IDBI BANK LIMITED',
 'IDFC FIRST BANK LIMITED',
 'INDUSIND BANK LTD',
 'JAMMU & KASHMIR BANK LTD',
 'KARNATAKA BANK LTD',
 'KARUR VYSYA BANK LTD',
 'KOTAK MAHINDRA BANK LTD.',
 'NAINITAL BANK LTD',
 'RBL BANK LTD',
 'SOUTH INDIAN BANK LTD',
 'TAMILNAD MERCANTILE BANK LTD',
 'YES BANK LTD.',
 'AB BANK PLC',
 'AMERICAN EXPRESS BANKING CORP.',
 'AUSTRALIA AND NEW ZEALAND BANKING GROUP LIMITED',
 'BANK OF AMERICA , NATIONAL ASSOCIATION',
 'BANK OF BAHRAIN & KUWAIT B.S.C.',
 'BANK OF CEYLON',
 'BANK OF CHINA LIMITED',
 'BANK OF NOVA SCOTIA',
 'BARCLAYS BANK PLC',
 'BNP PARIBAS',
 'CITIBANK N.A',
 'COOPERATIEVE RABOBANK U.A.',
 'CREDIT AGRICOLE CORPORATE AND INVESTMENT BANK',
 'CTBC BANK CO., LTD.',
 'DBS BANK INDIA LIMITED',
 'DEUTSCHE BANK AG',
 'DOHA BANK Q.P.S.C.',
 'EMIRATES NBD BANK (P.J.S.C.)',
 'FIRST ABU DHABI BANK PJSC',
 'FIRSTRAND BANK LTD',
 'INDUSTRIAL AND COMMERCIAL BANK OF CHINA',
 'INDUSTRIAL BANK OF KOREA',
 'JPMORGAN CHASE BANK NATIONAL ASSOCIATION',
 'JSC VTB BANK',
 'KEB HANA BANK',
 'KOOKMIN BANK',
 'MASHREQ BANK PSC',
 'MIZUHO BANK LTD',
 'MUFG BANK, LTD.',
 'NATWEST MARKETS PLC',
 'NONGHYUP BANK',
 'PT BANK MAYBANK INDONESIA TBK',
 'QATAR NATIONAL BANK (Q.P.S.C)',
 'SBERBANK',
 'SBM BANK (INDIA) LIMITED',
 'SHINHAN BANK',
 'SOCIETE GENERALE',
 'SONALI BANK PLC',
 'STANDARD CHARTERED BANK',
 'SUMITOMO MITSUI BANKING CORPORATION',
 'THE HONGKONG AND SHANGHAI BANKING CORPORATION LIMITED',
 'UBS AG',
 'UNITED OVERSEAS BANK LTD',
 'WOORI BANK',
 'AU SMALL FINANCE BANK LIMITED',
 'CAPITAL SMALL FINANCE BANK LIMITED',
 'EQUITAS SMALL FINANCE BANK LIMITED',
 'ESAF SMALL FINANCE BANK LIMITED',
 'JANA SMALL FINANCE BANK LIMITED',
 'NORTH EAST SMALL FINANCE BANK LIMITED',
 'SHIVALIK SMALL FINANCE BANK LIMITED',
 'SURYODAY SMALL FINANCE BANK LIMITED',
 'UJJIVAN SMALL FINANCE BANK LIMITED',
 'UNITY SMALL FINANCE BANK LIMITED',
 'UTKARSH SMALL FINANCE BANK LIMITED',
 'AIRTEL PAYMENTS BANK LIMITED',
 'FINO PAYMENTS BANK LIMITED',
 'INDIA POST PAYMENTS BANK LIMITED',
 'PAYTM PAYMENTS BANK LIMITED',
 'PAYMENTS BANKS',
 'AB BANK LIMITED',
 'CREDIT SUISSE AG',
 'KRUNG THAI BANK PUBLIC COMPANY LIMITED',
 'SONALI BANK',
 'FINCARE SMALL FINANCE BANK LIMITED',
 'ABU DHABI COMMERCIAL BANK PJSC',
 'HONGKONG AND SHANGHAI BANKING CORPN.LTD.',
 'THE ROYAL BANK OF SCOTLAND N.V.',
 'ALLAHABAD BANK',
 'ANDHRA BANK',
 'CORPORATION BANK',
 'ORIENTAL BANK OF COMMERCE',
 'SYNDICATE BANK',
 'UNITED BANK OF INDIA',
 'LAKSHMI VILAS BANK LTD',
 'WESTPAC BANKING CORPORATION',
 'DENA BANK',
 'VIJAYA BANK',
 'NATIONAL AUSTRALIA BANK',
 'IDFC BANK LIMITED',
 'STATE BANK OF BIKANER AND JAIPUR',
 'STATE BANK OF HYDERABAD',
 'STATE BANK OF MYSORE',
 'STATE BANK OF PATIALA',
 'STATE BANK OF TRAVANCORE',
 'STATE BANK OF INDIA AND ITS ASSOCIATES',
 'BHARATIYA MAHILA BANK LTD.',
 'NATIONALISED BANKS',
 'COMMONWEALTH BANK OF AUSTRALIA',
 'KBC BANK N.V.']

In [10]:
#Which banks are the largest in India in FY2024-25?

top_banks = (
    master[master["year"] == 2025]
    .sort_values("total_assets", ascending=False)
    [["bank_name", "total_assets"]]
    .head(10)
)

top_banks

               bank_name  total_assets
9    STATE BANK OF INDIA  6.676053e+06
19        HDFC BANK LTD.  3.910199e+06
20    ICICI BANK LIMITED  2.118240e+06
8   PUNJAB NATIONAL BANK  1.818171e+06
0         BANK OF BARODA  1.781247e+06
3            CANARA BANK  1.682850e+06
12     AXIS BANK LIMITED  1.609930e+06
11   UNION BANK OF INDIA  1.499856e+06
1          BANK OF INDIA  1.042582e+06
5            INDIAN BANK  8.734107e+05

In [11]:
master = master.sort_values(["bank_name", "year"])

In [16]:
master["asset_growth"] = (
    master
    .groupby("bank_name")["total_assets"]
    .pct_change() * 100
)

In [20]:
master[master["year"] == 2025].sort_values("asset_growth", ascending=False)[["bank_name", "asset_growth"]].head(10)

                                        bank_name  asset_growth
66                                       SBERBANK    163.739774
82          NORTH EAST SMALL FINANCE BANK LIMITED    156.731481
59                               MASHREQ BANK PSC    102.269665
56                                   JSC VTB BANK     77.445666
90               INDIA POST PAYMENTS BANK LIMITED     67.662114
88                   AIRTEL PAYMENTS BANK LIMITED     59.891896
50                   EMIRATES NBD BANK (P.J.S.C.)     51.064356
92                                 PAYMENTS BANKS     48.142260
45  CREDIT AGRICOLE CORPORATE AND INVESTMENT BANK     47.896701
55       JPMORGAN CHASE BANK NATIONAL ASSOCIATION     47.075145

In [22]:
master["deposit_growth"] = (
    master.groupby("bank_name")["deposits"].pct_change() * 100
)

In [23]:
#finding the deposit growth for the year 2025 

master[master["year"]==2025].sort_values("deposit_growth",ascending=False)[["bank_name","deposit_growth"]].head(10)

                           bank_name  deposit_growth
63                     NONGHYUP BANK     4780.116110
66                          SBERBANK      324.943735
51         FIRST ABU DHABI BANK PJSC      200.152958
56                      JSC VTB BANK      193.039197
64     PT BANK MAYBANK INDONESIA TBK      145.388861
86  UNITY SMALL FINANCE BANK LIMITED       83.731036
59                  MASHREQ BANK PSC       76.603334
39             BANK OF CHINA LIMITED       74.994757
50      EMIRATES NBD BANK (P.J.S.C.)       67.953987
90  INDIA POST PAYMENTS BANK LIMITED       67.459445

In [25]:
master["advance_growth"]=master.groupby("bank_name")["advances"].pct_change()*100

In [26]:
master[[
    "bank_name",
    "year",
    "asset_growth",
    "deposit_growth",
    "advance_growth"
]].head(20)

,bank_name,year,asset_growth,deposit_growth,advance_growth
898,AB BANK LIMITED,2016,NaN,NaN,NaN
802,AB BANK LIMITED,2017,-3.556650,-9.440305,2.517434
701,AB BANK LIMITED,2018,-12.367761,-14.178918,-20.634353
607,AB BANK LIMITED,2019,17.645200,26.545288,0.728989
507,AB BANK LIMITED,2020,-18.714743,-28.557897,7.974976
409,AB BANK LIMITED,2021,47.108941,83.079058,11.381098
315,AB BANK LIMITED,2022,14.910540,14.174574,-0.225447
221,AB BANK LIMITED,2023,-25.185932,-40.214288,-11.216732
126,AB BANK LIMITED,2024,69.639956,67.510522,25.661542
33,AB BANK PLC,2025,NaN,NaN,NaN
899,ABU DHABI COMMERCIAL BANK PJSC,2016,NaN,NaN,NaN
803,ABU DHABI COMMERCIAL BANK PJSC,2017,29.039432,36.178112,15.744690
702,ABU DHABI COMMERCIAL BANK PJSC,2018,-1.648202,-18.178197,-12.134812
608,ABU DHABI COMMERCIAL BANK PJSC,2019,-17.717027,-10.967835,-24.854018
508,ABU DHABI COMMERCIAL BANK PJSC,2020,-88.339182,NaN,NaN
410,ABU DHABI COMMERCIAL BANK PJSC,2021,-6.444628,NaN,NaN
316,ABU DHABI COMMERCIAL BANK PJSC,2022,-3.302583,NaN,NaN
371,AIRTEL PAYMENTS BANK LIMITED,2022,NaN,NaN,NaN
277,AIRTEL PAYMENTS BANK LIMITED,2023,42.199608,69.180640,NaN
183,AIRTEL PAYMENTS BANK LIMITED,2024,55.217998,56.677843,NaN

In [31]:
master["calculated_nii"] = (
    master["interest_earned"] - master["interest_expended"]
)

master["nii_difference"] = (
    master["net_interest_income"] - master["calculated_nii"]
)

master["nii_difference"].describe()

count    9.250000e+02
mean     2.162075e-09
std      4.721642e-07
min     -5.000000e-06
25%     -3.552714e-15
50%      0.000000e+00
75%      7.105427e-15
max      1.000000e-05
Name: nii_difference, dtype: float64

In [32]:
master[master["year"]==2025].sort_values("net_profit",ascending=False)[["bank_name","net_profit"]].head(10)

                   bank_name  net_profit
9        STATE BANK OF INDIA  70900.6281
19            HDFC BANK LTD.  67347.3581
20        ICICI BANK LIMITED  47226.9927
12         AXIS BANK LIMITED  26373.4819
0             BANK OF BARODA  19581.1521
11       UNION BANK OF INDIA  17987.1462
3                CANARA BANK  17026.6715
8       PUNJAB NATIONAL BANK  16630.2012
27  KOTAK MAHINDRA BANK LTD.  16450.0785
5                INDIAN BANK  10918.2940

In [33]:
master[master["year"]==2025].sort_values("return_on_assets",ascending=False)[["bank_name","return_on_assets"]].head(10)

                                   bank_name  return_on_assets
56                              JSC VTB BANK              5.28
33                               AB BANK PLC              5.10
66                                  SBERBANK              4.48
64             PT BANK MAYBANK INDONESIA TBK              3.64
55  JPMORGAN CHASE BANK NATIONAL ASSOCIATION              2.93
86          UNITY SMALL FINANCE BANK LIMITED              2.88
74                                    UBS AG              2.74
27                  KOTAK MAHINDRA BANK LTD.              2.65
89                FINO PAYMENTS BANK LIMITED              2.47
20                        ICICI BANK LIMITED              2.41

In [36]:
#Finding the results for top 5 banks based on assest in the year 2025

master[master["year"]==2025].sort_values("total_assets",ascending=False)[["bank_name","total_assets","net_profit","return_on_assets"]].head(10)

               bank_name  total_assets  net_profit  return_on_assets
9    STATE BANK OF INDIA  6.676053e+06  70900.6281              1.10
19        HDFC BANK LTD.  3.910199e+06  67347.3581              1.91
20    ICICI BANK LIMITED  2.118240e+06  47226.9927              2.41
8   PUNJAB NATIONAL BANK  1.818171e+06  16630.2012              0.97
0         BANK OF BARODA  1.781247e+06  19581.1521              1.16
3            CANARA BANK  1.682850e+06  17026.6715              1.09
12     AXIS BANK LIMITED  1.609930e+06  26373.4819              1.74
11   UNION BANK OF INDIA  1.499856e+06  17987.1462              1.26
1          BANK OF INDIA  1.042582e+06   9219.0199              0.90
5            INDIAN BANK  8.734107e+05  10918.2940              1.32

In [37]:
master["profit_growth"] = (
    master.groupby("bank_name")["net_profit"].pct_change() * 100
)

In [38]:
master.to_csv(
    "../02_Cleaned_Data/bank_master.csv",
    index=False
)